""" Vocabularies
"""

vocabs = {
  'themes': (
    ('default', 'Default'),
    ('air', 'Air pollution'),
    ('biodiversity', 'Biodiversity'),
    ('chemicals', 'Chemicals'),
    ('climate', 'Climate change'),
    ('coasts_seas', 'Coasts and seas'),
    ('economy', 'Green economy'),
    ('energy', 'Energy'),
    ('fisheries', 'Fisheries'),
    ('households', 'Households consumption'),
    ('human', 'Environment and health'),
    ('industry', 'Industry'),
    ('landuse', 'Industry'),
    ('natural', 'Natural resources'),
    ('noise', 'Noise'),
    ('other_issues', 'Various other issues'),
    ('policy', 'Policy instruments'),
    ('regions', 'Specific regions'),
    ('scenarios', 'Environmental scenarios'),
    ('soil', 'Soil'),
    ('technology', 'Environmental technology'),
    ('tourism', 'Tourism'),
    ('urban', 'Urban environment'),
    ('waste', 'Waste and material resources'),
    ('water', 'Water'),
),
  'countries': (
    ('default', 'Select your country'),
    ('AND','ANDORRA'),
    ('AUT','AUSTRIA'),
    ('BLR','BELARUS'),
    ('BEL','BELGIUM'),
    ('BIH','BOSNIA AND HERZEGOWINA'),
    ('BGR','BULGARIA'),
    ('HRV','CROATIA (local name: Hrvatska)'),
    ('CYP','CYPRUS'),
    ('CZE','CZECH REPUBLIC'),
    ('DNK','DENMARK'),
    ('SLV','EL SALVADOR'),
    ('EST','ESTONIA'),
    ('FJI','FIJI'),
    ('FIN','FINLAND'),
    ('FRA','FRANCE'),
    ('GEO','GEORGIA'),
    ('DEU','GERMANY'),
    ('GRC','GREECE'),
    ('GRL','GREENLAND'),
    ('HUN','HUNGARY'),
    ('ISL','ICELAND'),
    ('IRL','IRELAND'),
    ('ITA','ITALY'),
    ('LVA','LATVIA'),
    ('LTU','LITHUANIA'),
    ('LUX','LUXEMBOURG'),
    ('MKD','THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA,'),
    ('MLT','MALTA'),
    ('MEX','MEXICO'),
    ('MCO','MONACO'),
    ('NLD','NETHERLANDS'),
    ('NOR','NORWAY'),
    ('POL','POLAND'),
    ('PRT','PORTUGAL'),
    ('ROM','ROMANIA'),
    ('RUS','RUSSIAN FEDERATION'),
    ('SVK','SLOVAKIA (Slovak Republic)'),
    ('SVN','SLOVENIA'),
    ('ESP','SPAIN'),
    ('SWE','SWEDEN'),
    ('CHE','SWITZERLAND'),
    ('TUR','TURKEY'),
    ('GBR','UNITED KINGDOM'),
    ('ZZZ','Other'),
)}

